name: Auto Create Issues from Tasks

on:
  push:
    branches:
      - master

jobs:
  create-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install gh cli
        run: sudo apt-get install gh
      - name: Install dependencies
        run: npm install
      - name: Create issues from all tasks.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node scripts/create-issues-from-tasks.cjs
